Added a way to hide the tag of admins without removing other features
Hexer10/HexTags pull request #78
Opened 2020-10-25 19:21 UTC by Sarrus1

My admins asked me to implement a command to make them anonymous on the server.
The `!toggletag` commands works fine but it removes the tag entirely.
This new `!anonymous` command disables tags for admins and people who had a their steamid referenced in the config, while keeping other tags like Ranks calculated with rankme etc.

**COMPILES** ✅

**TESTED** ✅

2021-04-01 13:01 UTC, fejmek commented
When the tag is hidden with sm_anonymous and hidden admin join the server, such an error will appear:
```
L 04/01/2021 - 14:50:06: [SM] Exception reported: Client index 2 is not valid
L 04/01/2021 - 14:50:06: [SM] Blaming: hextags.smx
L 04/01/2021 - 14:50:06: [SM] Call stack trace:
L 04/01/2021 - 14:50:06: [SM] [0] CS_GetClientClanTag
L 04/01/2021 - 14:50:06: [SM] [1] Line 542, /Users/charleszablit/Documents/Perso/Dev/Sourcemod/HexTags/addons/sourcemod/scripting/hextags.sp::OnClientCookiesCached
```

2021-04-01 17:23 UTC, Sarrus1 commented
I'll try to take a look tomorrow. In the meantime, do you mine cropping the path of the file so that it doesn't include the username, like : `Line 542, HexTags/addons/sourcemod/scripting/hextags.sp::OnClientCookiesCached` so it doesn't contain personal informations?

2021-04-02 16:51 UTC, Sarrus1 commented
@fejmek Try with the latest build from my branch [here](https://github.com/Sarrus1/HexTags/blob/master/addons/sourcemod/plugins/hextags.smx). I don't think @Hexer10 is going to merge this.

2021-04-02 18:02 UTC, fejmek commented
@Sarrus1 error resolved :D

2021-05-31 09:58 UTC, Hexer10 requested changes
Sorry for the time it took to review this. Right now I'm having school exams, and I started focusing on other projects, so I had little to no time to work on this.

However your PR looks file, there are just some small quirks to fix and I'll merge it

2021-05-31 09:58 UTC, Hexer10 commented on addons/sourcemod/scripting/hextags.sp
> +	g_hAnonymousCookie = RegClientCookie("AnonymousCookie", "Plugin that defines wether or not an admin is anonymous.", CookieAccess_Protected);
I would stick with the `HexTags_` prefix for the cookies

2021-05-31 09:58 UTC, Hexer10 commented on addons/sourcemod/scripting/hextags.sp
> +	RegAdminCmd("sm_anonymous", Cmd_Anonymous, ADMFLAG_GENERIC|ADMFLAG_CUSTOM6, "This allows admins to hide their tags");
I think it's better to just leave the `ADMFLAG_GENERIC` flag and if users want to change the permission they could set it in the admin override

2021-05-31 09:58 UTC, Hexer10 commented on addons/sourcemod/scripting/hextags.sp
> +		}
The code in the two if branches is pretty much the same except for the Chat  messages so you could just to smth like:
```c
cookieValue = !cookieValue;
g_hAnonymous[client] = cookieValue == 1;
IntToString(cookieValue, sCookieValue, sizeof(sCookieValue));
SetClientCookie(client, hVibilityAdminsCookie, sCookieValue);
LoadTags(client);
char sTag[32];
CS_GetClientClanTag(client, sTag, sizeof(sTag));
if (!cookieValue)
{
	ReplyToCommand(client, "[SM] You are no longer anonymous. Your tag is %s", selectedTags[client].ScoreTag);
} 
else 
{
	ReplyToCommand(client, "[SM] You are now anonymous. Your tag is %s", selectedTags[client].ScoreTag);
}		
if (StrEqual(sTag, selectedTags[client].ScoreTag))
{
	return Plugin_Handled;
}
CS_SetClientClanTag(client, selectedTags[client].ScoreTag);
```

2022-02-16 16:51 UTC, merged